package model;
// Generated Dec 10, 2014 12:02:06 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer empId;
     private String name;
     private String email;
     private Date dob;

    public Employee() {
    }

    public Employee(String name, String email, Date dob) {
       this.name = name;
       this.email = email;
       this.dob = dob;
    }
   
    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDob() {
        return this.dob;
    }
    
    public void setDob(Date dob) {
        this.dob = dob;
    }




}


